### ISSUE TITLE
fix styling of `m-textarea` when developer wants 100% width

### ISSUE THREAD

**Issue by stackoverfloweth** [PrefectHQ/miter-design#205]
current hardcoded values requires this style block to create full-width textarea

```scss
.work-queue-create-panel__textarea {
  width: 100%;
  margin-inline-start: 0;

  .textarea__miter {
    width: 100%;
  }
}
```
